language: python

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda info -a

install:
  - conda env create -n test-env --file ci/travis_demo.yml
  - conda install --yes -n test-env nose flake8
  - source activate test-env
  - pip install -e .

script:
  - source activate test-env
  - nosetests -v travis_demo --with-coverage --cover-package=travis_demo
  - flake8 travis_demo setup.py
